// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxrBqYMvB6KqxHc6HfLKt6GH6VnFWvPZc',
    appId: '1:941566958830:web:085f116de189601dac27ff',
    messagingSenderId: '941566958830',
    projectId: 'sirekmobile-9458a',
    authDomain: 'sirekmobile-9458a.firebaseapp.com',
    storageBucket: 'sirekmobile-9458a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMFymMZ7nnztA0HD-a1rYlWZjAosO--4',
    appId: '1:941566958830:android:fa76464d73ab4bb8ac27ff',
    messagingSenderId: '941566958830',
    projectId: 'sirekmobile-9458a',
    storageBucket: 'sirekmobile-9458a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCyZwXhZPFsYlRxV6_KT6SxkMZwppuAo',
    appId: '1:941566958830:ios:33f0c5b90e66239bac27ff',
    messagingSenderId: '941566958830',
    projectId: 'sirekmobile-9458a',
    storageBucket: 'sirekmobile-9458a.firebasestorage.app',
    iosBundleId: 'com.example.sirek',
  );
}
